Add low_latency_interco and peripheral_interco sources to Bender.yml
pulp-platform/cluster_interconnect pull request #5
Opened 2020-11-03 15:23 UTC by micprog

2020-11-03 17:30 UTC, accuminium requested changes

2020-11-03 17:30 UTC, accuminium commented on Bender.yml
> +      - rtl_low_latency_interco
```suggestion
      - rtl/low_latency_interco
```
Typo, right?

2020-11-03 17:39 UTC, accuminium commented
This PR brings back a discussion from a while ago: are [`low_latency_interco`](https://github.com/pulp-platform/cluster_interconnect/tree/master/rtl/low_latency_interco) and [`peripheral_interco`](https://github.com/pulp-platform/cluster_interconnect/tree/master/rtl/peripheral_interco) going to stay supported as full standalone implementations, or should they be implemented using the components in the [`tcdm_interconnect`](https://github.com/pulp-platform/cluster_interconnect/tree/master/rtl/tcdm_interconnect) folder? From the top of my head:
- The [`tcdm_interconnect` module](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/tcdm_interconnect/tcdm_interconnect.sv) already implements the functionality of [`XBAR_TCDM`](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/low_latency_interco/XBAR_TCDM.sv), the top-level module of `low_latency_interco`, except for the test-and-set, which is replaced by RISC-V-compliant atomic operations executed by an [`amo_shim` module](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/tcdm_interconnect/amo_shim.sv) in front of a TCDM bank.
- The [`tcdm_interconnect` module](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/tcdm_interconnect/tcdm_interconnect.sv) can also be configured to implement the functionality of [`XBAR_PE`](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/peripheral_interco/XBAR_PE.sv), the top-level module of `peripheral_interco`.

Any thoughts? Especially from @suehtamacv as maintainer of this repository?

2020-11-03 18:02 UTC, micprog commented on Bender.yml
> +      - rtl_low_latency_interco
Oops, sorry about that

2020-11-04 13:37 UTC, suehtamacv commented
Thanks a lot for this MR, @micprog!

Why do we need to bump the version of the common cells module?

2020-11-04 13:44 UTC, micprog commented
I only bumped common_cells because other repos depended on v1.13.1, helping to avoid extra steps in bender, but I believe the changes are not significant: https://github.com/pulp-platform/common_cells/compare/v1.13.0...v1.13.1

2020-11-04 13:54 UTC, suehtamacv commented
> This PR brings back a discussion from a while ago: are [`low_latency_interco`](https://github.com/pulp-platform/cluster_interconnect/tree/master/rtl/low_latency_interco) and [`peripheral_interco`](https://github.com/pulp-platform/cluster_interconnect/tree/master/rtl/peripheral_interco) going to stay supported as full standalone implementations, or should they be implemented using the components in the [`tcdm_interconnect`](https://github.com/pulp-platform/cluster_interconnect/tree/master/rtl/tcdm_interconnect) folder? From the top of my head:
> 
>     * The [`tcdm_interconnect` module](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/tcdm_interconnect/tcdm_interconnect.sv) already implements the functionality of [`XBAR_TCDM`](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/low_latency_interco/XBAR_TCDM.sv), the top-level module of `low_latency_interco`, except for the test-and-set, which is replaced by RISC-V-compliant atomic operations executed by an [`amo_shim` module](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/tcdm_interconnect/amo_shim.sv) in front of a TCDM bank.
> 
>     * The [`tcdm_interconnect` module](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/tcdm_interconnect/tcdm_interconnect.sv) can also be configured to implement the functionality of [`XBAR_PE`](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/peripheral_interco/XBAR_PE.sv), the top-level module of `peripheral_interco`.
> 
> 
> Any thoughts? Especially from @suehtamacv as maintainer of this repository?

Recent designs that depend on this module are using `tcdm_interconnect`. Afaik, the only design that still relies upon `XBAR_TCDM` is `pulp-cluster`. Although it would be possible to deprecate `XBAR_TCDM` in favor of `tcdm_interconnect`, that is not a seamless change, and there are hardware costs for that. Particularly since both `XBAR_TCDM` and `XBAR_PE` were highly tuned for their target designs. 

Taking your point a step further, it might be possible to deprecate the designs of this repo entirely. We could use `common_cell`'s `stream_xbar` as a general replacement (since it supports the same request/grant handshake as TCDM). The solution might not be optimal, though, since `tcdm_interconnect` was built with the underlying hypothesis that the slaves answer with a constant latency. Since `stream_xbar` does not have this hypothesis, building an interconnect with it would require a full handshake for both the request and the response paths---although a wrapper can hide this from the masters. What do you think, @accuminium?

2020-11-04 14:13 UTC, FrancescoConti commented
@suehtamacv what is the difference in area/power/timing between a fully logarithmic interconnect using `tcdm_interconnect` and the `XBAR_TCDM`?

2020-11-04 15:10 UTC, accuminium commented
> Taking your point a step further, it might be possible to deprecate the designs of this repo entirely. We could use `common_cell`'s `stream_xbar` as a general replacement (since it supports the same request/grant handshake as TCDM). The solution might not be optimal, though, since `tcdm_interconnect` was built with the underlying hypothesis that the slaves answer with a constant latency. Since `stream_xbar` does not have this hypothesis, building an interconnect with it would require a full handshake for both the request and the response paths---although a wrapper can hide this from the masters. What do you think, @accuminium?

I think we cannot and should not go that far.  Most cluster designs maintain the fixed latency on the response path of the TCDM as architectural feature.  As long as that is the case, it is worth having an interconnect optimized for it.

2020-11-04 15:20 UTC, accuminium commented
> @suehtamacv what is the difference in area/power/timing between a fully logarithmic interconnect using `tcdm_interconnect` and the `XBAR_TCDM`?

The `tcdm_interconnect` with the `LIC` option has the same topology as `XBAR_TCDM`.  Michael did a [post-synthesis scalability analysis of the TCDM interconnect in different configurations in GF22FDX (HP libs, slow-slow, closed at 1 GHz, without BB)](https://github.com/pulp-platform/cluster_interconnect/blob/master/rtl/tcdm_interconnect/README.md#scalability-analysis).  Maybe @suehtamacv has more results from recent experiments?

For a really convincing apples-to-apples comparison, @FrancescoConti do you think it would be feasible and meaningful to exchange the cluster interconnect in the latest tapeout, and rerun at least synthesis?

2020-11-04 15:23 UTC, accuminium commented
Btw @suehtamacv: I am not suggesting that this discussion should prevent this PR from being merged.  But we should really have the discussion, otherwise we will never converge or have evidence that we cannot converge.

2020-11-04 15:26 UTC, accuminium approved these changes

2020-11-05 10:01 UTC, suehtamacv commented
> > Taking your point a step further, it might be possible to deprecate the designs of this repo entirely. We could use `common_cell`'s `stream_xbar` as a general replacement (since it supports the same request/grant handshake as TCDM). The solution might not be optimal, though, since `tcdm_interconnect` was built with the underlying hypothesis that the slaves answer with a constant latency. Since `stream_xbar` does not have this hypothesis, building an interconnect with it would require a full handshake for both the request and the response paths---although a wrapper can hide this from the masters. What do you think, @accuminium?
> 
> I think we cannot and should not go that far. Most cluster designs maintain the fixed latency on the response path of the TCDM as architectural feature. As long as that is the case, it is worth having an interconnect optimized for it.

I agree. But this interconnect can be built from the IPs in `common_cells`: a `stream_xbar` for the request path, the request grant signal being registered for `LATENCY` cycles to produce the `rvalid` signal, and a `stream_mux` for the response path. That is pretty similar to the internal organization of `XBAR_TCDM`. The benefit of it is the reduced code duplication.

2020-11-05 10:02 UTC, suehtamacv commented
> @suehtamacv what is the difference in area/power/timing between a fully logarithmic interconnect using `tcdm_interconnect` and the `XBAR_TCDM`?

I do not have this result. That analysis that Andreas quoted is for the `tcdm_interconnect`, but afaik there are no comparisons with `XBAR_TCDM`. I will look into this in the next few weeks -- and move this discussion to a separate issue.

2020-11-05 10:13 UTC, suehtamacv commented
Thanks a lot for this PR, @micprog! Merging.

2020-11-05 10:13 UTC, merged